==2318538== Memcheck, a memory error detector
==2318538== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==2318538== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==2318538== Command: python3 /home/sam/working/SPECT_issues/resolution_issue_stir.py
==2318538== 
==2318538== 
==2318538== HEAP SUMMARY:
==2318538==     in use at exit: 1,593,433 bytes in 1,176 blocks
==2318538==   total heap usage: 184,434 allocs, 183,258 frees, 106,197,495 bytes allocated
==2318538== 
==2318538== 64 bytes in 1 blocks are definitely lost in loss record 79 of 476
==2318538==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==2318538==    by 0x400F21D: malloc (rtld-malloc.h:56)
==2318538==    by 0x400F21D: resize_scopes (dl-open.c:295)
==2318538==    by 0x400F21D: dl_open_worker_begin (dl-open.c:707)
==2318538==    by 0x4B2EC27: _dl_catch_exception (dl-error-skeleton.c:208)
==2318538==    by 0x400DF99: dl_open_worker (dl-open.c:782)
==2318538==    by 0x4B2EC27: _dl_catch_exception (dl-error-skeleton.c:208)
==2318538==    by 0x400E34D: _dl_open (dl-open.c:883)
==2318538==    by 0x4A4A6BB: dlopen_doit (dlopen.c:56)
==2318538==    by 0x4B2EC27: _dl_catch_exception (dl-error-skeleton.c:208)
==2318538==    by 0x4B2ECF2: _dl_catch_error (dl-error-skeleton.c:227)
==2318538==    by 0x4A4A1AD: _dlerror_run (dlerror.c:138)
==2318538==    by 0x4A4A747: dlopen_implementation (dlopen.c:71)
==2318538==    by 0x4A4A747: dlopen@@GLIBC_2.34 (dlopen.c:81)
==2318538==    by 0x36D60A: ??? (in /usr/bin/python3.10)
==2318538== 
==2318538== 568 bytes in 1 blocks are possibly lost in loss record 92 of 476
==2318538==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==2318538==    by 0x229637: _PyObject_GC_NewVar (in /usr/bin/python3.10)
==2318538==    by 0x24FE7C: ??? (in /usr/bin/python3.10)
==2318538==    by 0x2686DD: _PyFunction_Vectorcall (in /usr/bin/python3.10)
==2318538==    by 0x250F51: _PyEval_EvalFrameDefault (in /usr/bin/python3.10)
==2318538==    by 0x26870B: _PyFunction_Vectorcall (in /usr/bin/python3.10)
==2318538==    by 0x250F51: _PyEval_EvalFrameDefault (in /usr/bin/python3.10)
==2318538==    by 0x26870B: _PyFunction_Vectorcall (in /usr/bin/python3.10)
==2318538==    by 0x250E0C: _PyEval_EvalFrameDefault (in /usr/bin/python3.10)
==2318538==    by 0x26870B: _PyFunction_Vectorcall (in /usr/bin/python3.10)
==2318538==    by 0x250E0C: _PyEval_EvalFrameDefault (in /usr/bin/python3.10)
==2318538==    by 0x26870B: _PyFunction_Vectorcall (in /usr/bin/python3.10)
==2318538== 
==2318538== 624 bytes in 1 blocks are possibly lost in loss record 254 of 476
==2318538==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==2318538==    by 0x229637: _PyObject_GC_NewVar (in /usr/bin/python3.10)
==2318538==    by 0x24FE7C: ??? (in /usr/bin/python3.10)
==2318538==    by 0x2764AF: ??? (in /usr/bin/python3.10)
==2318538==    by 0x2520D0: _PyEval_EvalFrameDefault (in /usr/bin/python3.10)
==2318538==    by 0x26870B: _PyFunction_Vectorcall (in /usr/bin/python3.10)
==2318538==    by 0x25D82C: _PyObject_FastCallDictTstate (in /usr/bin/python3.10)
==2318538==    by 0x27354B: _PyObject_Call_Prepend (in /usr/bin/python3.10)
==2318538==    by 0x38C1DF: ??? (in /usr/bin/python3.10)
==2318538==    by 0x25E5EA: _PyObject_MakeTpCall (in /usr/bin/python3.10)
==2318538==    by 0x257907: _PyEval_EvalFrameDefault (in /usr/bin/python3.10)
==2318538==    by 0x2764E0: ??? (in /usr/bin/python3.10)
==2318538== 
==2318538== 704 bytes in 1 blocks are possibly lost in loss record 259 of 476
==2318538==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==2318538==    by 0x229637: _PyObject_GC_NewVar (in /usr/bin/python3.10)
==2318538==    by 0x24FE7C: ??? (in /usr/bin/python3.10)
==2318538==    by 0x25D753: _PyObject_FastCallDictTstate (in /usr/bin/python3.10)
==2318538==    by 0x2AA5AC: ??? (in /usr/bin/python3.10)
==2318538==    by 0x25E536: _PyObject_MakeTpCall (in /usr/bin/python3.10)
==2318538==    by 0x25B982: ??? (in /usr/bin/python3.10)
==2318538==    by 0x25B50A: ??? (in /usr/bin/python3.10)
==2318538==    by 0x2520D0: _PyEval_EvalFrameDefault (in /usr/bin/python3.10)
==2318538==    by 0x341E55: ??? (in /usr/bin/python3.10)
==2318538==    by 0x341CF5: PyEval_EvalCode (in /usr/bin/python3.10)
==2318538==    by 0x347B0C: ??? (in /usr/bin/python3.10)
==2318538== 
==2318538== 832 bytes in 1 blocks are possibly lost in loss record 264 of 476
==2318538==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==2318538==    by 0x229637: _PyObject_GC_NewVar (in /usr/bin/python3.10)
==2318538==    by 0x24FE7C: ??? (in /usr/bin/python3.10)
==2318538==    by 0x2686DD: _PyFunction_Vectorcall (in /usr/bin/python3.10)
==2318538==    by 0x250E0C: _PyEval_EvalFrameDefault (in /usr/bin/python3.10)
==2318538==    by 0x26870B: _PyFunction_Vectorcall (in /usr/bin/python3.10)
==2318538==    by 0x250E0C: _PyEval_EvalFrameDefault (in /usr/bin/python3.10)
==2318538==    by 0x26870B: _PyFunction_Vectorcall (in /usr/bin/python3.10)
==2318538==    by 0x250E0C: _PyEval_EvalFrameDefault (in /usr/bin/python3.10)
==2318538==    by 0x26870B: _PyFunction_Vectorcall (in /usr/bin/python3.10)
==2318538==    by 0x250E0C: _PyEval_EvalFrameDefault (in /usr/bin/python3.10)
==2318538==    by 0x26870B: _PyFunction_Vectorcall (in /usr/bin/python3.10)
==2318538== 
==2318538== 1,068 bytes in 1 blocks are possibly lost in loss record 274 of 476
==2318538==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==2318538==    by 0x247F6E: ??? (in /usr/bin/python3.10)
==2318538==    by 0x2460C4: ??? (in /usr/bin/python3.10)
==2318538==    by 0x246A7E: ??? (in /usr/bin/python3.10)
==2318538==    by 0x24652B: ??? (in /usr/bin/python3.10)
==2318538==    by 0x34131F: ??? (in /usr/bin/python3.10)
==2318538==    by 0x3512A4: ??? (in /usr/bin/python3.10)
==2318538==    by 0x267853: ??? (in /usr/bin/python3.10)
==2318538==    by 0x2568A1: _PyEval_EvalFrameDefault (in /usr/bin/python3.10)
==2318538==    by 0x26870B: _PyFunction_Vectorcall (in /usr/bin/python3.10)
==2318538==    by 0x2520D0: _PyEval_EvalFrameDefault (in /usr/bin/python3.10)
==2318538==    by 0x26870B: _PyFunction_Vectorcall (in /usr/bin/python3.10)
==2318538== 
==2318538== 6,000 bytes in 15 blocks are possibly lost in loss record 458 of 476
==2318538==    at 0x484DA83: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==2318538==    by 0x40147D9: calloc (rtld-malloc.h:44)
==2318538==    by 0x40147D9: allocate_dtv (dl-tls.c:375)
==2318538==    by 0x40147D9: _dl_allocate_tls (dl-tls.c:634)
==2318538==    by 0x4A4F834: allocate_stack (allocatestack.c:430)
==2318538==    by 0x4A4F834: pthread_create@@GLIBC_2.34 (pthread_create.c:647)
==2318538==    by 0x797525F: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==2318538==    by 0x796BA10: GOMP_parallel (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==2318538==    by 0x650B9F3: stir::BackProjectorByBin::set_up(std::shared_ptr<stir::ProjDataInfo const> const&, std::shared_ptr<stir::DiscretisedDensity<3, float> const> const&) (BackProjectorByBin.cxx:86)
==2318538==    by 0x65679FA: stir::ProjectorByBinPair::set_up(std::shared_ptr<stir::ProjDataInfo const> const&, std::shared_ptr<stir::DiscretisedDensity<3, float> const> const&) (ProjectorByBinPair.cxx:49)
==2318538==    by 0x6567DEC: stir::ProjectorByBinPairUsingProjMatrixByBin::set_up(std::shared_ptr<stir::ProjDataInfo const> const&, std::shared_ptr<stir::DiscretisedDensity<3, float> const> const&) (ProjectorByBinPairUsingProjMatrixByBin.cxx:89)
==2318538==    by 0x6244968: _wrap_ProjectorByBinPairUsingProjMatrixByBin_set_up (stirPYTHON_wrap.cxx:126905)
==2318538==    by 0x24C9DF: ??? (in /usr/bin/python3.10)
==2318538==    by 0x250F51: _PyEval_EvalFrameDefault (in /usr/bin/python3.10)
==2318538==    by 0x341E55: ??? (in /usr/bin/python3.10)
==2318538== 
==2318538== 45,827 bytes in 22 blocks are possibly lost in loss record 469 of 476
==2318538==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==2318538==    by 0x247F6E: ??? (in /usr/bin/python3.10)
==2318538==    by 0x2460C4: ??? (in /usr/bin/python3.10)
==2318538==    by 0x246948: ??? (in /usr/bin/python3.10)
==2318538==    by 0x24652B: ??? (in /usr/bin/python3.10)
==2318538==    by 0x246A7E: ??? (in /usr/bin/python3.10)
==2318538==    by 0x24652B: ??? (in /usr/bin/python3.10)
==2318538==    by 0x34131F: ??? (in /usr/bin/python3.10)
==2318538==    by 0x3512A4: ??? (in /usr/bin/python3.10)
==2318538==    by 0x267853: ??? (in /usr/bin/python3.10)
==2318538==    by 0x2568A1: _PyEval_EvalFrameDefault (in /usr/bin/python3.10)
==2318538==    by 0x26870B: _PyFunction_Vectorcall (in /usr/bin/python3.10)
==2318538== 
==2318538== 127,030 bytes in 70 blocks are possibly lost in loss record 473 of 476
==2318538==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==2318538==    by 0x2900C7: PyUnicode_Substring (in /usr/bin/python3.10)
==2318538==    by 0x277B27: ??? (in /usr/bin/python3.10)
==2318538==    by 0x250F51: _PyEval_EvalFrameDefault (in /usr/bin/python3.10)
==2318538==    by 0x26870B: _PyFunction_Vectorcall (in /usr/bin/python3.10)
==2318538==    by 0x250E0C: _PyEval_EvalFrameDefault (in /usr/bin/python3.10)
==2318538==    by 0x341E55: ??? (in /usr/bin/python3.10)
==2318538==    by 0x341CF5: PyEval_EvalCode (in /usr/bin/python3.10)
==2318538==    by 0x347B0C: ??? (in /usr/bin/python3.10)
==2318538==    by 0x268968: ??? (in /usr/bin/python3.10)
==2318538==    by 0x2532C0: _PyEval_EvalFrameDefault (in /usr/bin/python3.10)
==2318538==    by 0x26870B: _PyFunction_Vectorcall (in /usr/bin/python3.10)
==2318538== 
==2318538== LEAK SUMMARY:
==2318538==    definitely lost: 64 bytes in 1 blocks
==2318538==    indirectly lost: 0 bytes in 0 blocks
==2318538==      possibly lost: 182,653 bytes in 112 blocks
==2318538==    still reachable: 1,410,716 bytes in 1,063 blocks
==2318538==         suppressed: 0 bytes in 0 blocks
==2318538== Reachable blocks (those to which a pointer was found) are not shown.
==2318538== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==2318538== 
==2318538== For lists of detected and suppressed errors, rerun with: -s
==2318538== ERROR SUMMARY: 9 errors from 9 contexts (suppressed: 0 from 0)
